<JurosScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        md_bg_color: 0.95, 0.95, 0.97, 1
        
        MDTopAppBar:
            title: "Juros e Amortização"
            elevation: 2
            left_action_items: [["arrow-left", lambda x: setattr(root.manager, 'current', 'inicial')]]
        
        # --- BOTÕES DE NAVEGAÇÃO INTERNA ---
        MDBoxLayout:
            size_hint_y: None
            height: "65dp"
            padding: "5dp"
            spacing: "5dp"
            
            MDFillRoundFlatButton:
                text: "TEORIA"
                icon: "lightbulb-on"
                size_hint_x: 0.33
                on_release: sm_juros.current = "aba_teoria"
            
            MDFillRoundFlatButton:
                text: "PRATICAR"
                icon: "calculator-variant"
                size_hint_x: 0.33
                md_bg_color: 0.2, 0.6, 0.2, 1
                on_release: sm_juros.current = "aba_pratica"

            MDFillRoundFlatButton:
                text: "AMORTIZAÇÃO"
                icon: "bank"
                size_hint_x: 0.33
                md_bg_color: 0.7, 0.3, 0.1, 1
                on_release: sm_juros.current = "aba_financiamento"

        # --- GESTOR DAS SUB-ABAS ---
        MDScreenManager:
            id: sm_juros

            # ==========================================
            # ABA 1: TEORIA INTERATIVA
            # ==========================================
            MDScreen:
                name: "aba_teoria"
                ScrollView:
                    MDBoxLayout:
                        orientation: 'vertical'
                        padding: "20dp"
                        spacing: "20dp"
                        adaptive_height: True

                        MDCard:
                            orientation: "vertical"
                            size_hint: 1, None
                            height: "140dp"
                            padding: "16dp"
                            radius: [15]
                            elevation: 1
                            
                            MDBoxLayout:
                                spacing: "10dp"
                                MDIcon:
                                    icon: "file-pdf-box"
                                    theme_text_color: "Custom"
                                    text_color: 1, 0, 0, 1 
                                    font_size: "32sp"
                                MDLabel:
                                    text: "Guia de Juros Compostos"
                                    bold: True
                                    font_style: "Subtitle1"
                                    adaptive_height: True
                            
                            MDLabel:
                                text: "Material de apoio para entender o crescimento exponencial."
                                font_style: "Caption"
                                theme_text_color: "Secondary"
                                adaptive_height: True

                            MDRaisedButton:
                                text: "ABRIR GUIA"
                                pos_hint: {"right": 1}
                                on_release: root.abrir_guia_juros()

                        MDCard:
                            orientation: "vertical"
                            padding: "20dp"
                            spacing: "15dp"
                            radius: [15]
                            adaptive_height: True
                            
                            MDLabel:
                                text: "O Efeito Bola de Neve"
                                bold: True
                                font_style: "H6"
                                theme_text_color: "Primary"
                                adaptive_height: True
                                
                            MDLabel:
                                text: "Os juros compostos não crescem em linha reta. Como o sistema calcula juros sobre os juros do mês anterior, o teu dinheiro começa a multiplicar-se cada vez mais rápido!"
                                theme_text_color: "Secondary"
                                adaptive_height: True

                        MDCard:
                            orientation: "vertical"
                            padding: "20dp"
                            spacing: "20dp"
                            radius: [15]
                            adaptive_height: True
                            md_bg_color: 0.9, 0.95, 1, 1
                            
                            MDLabel:
                                text: "Deslize para ver o tempo a passar:"
                                bold: True
                                font_style: "Subtitle2"
                                adaptive_height: True

                            MDSlider:
                                id: slider_tempo
                                min: 1
                                max: 120
                                value: 1
                                hint: True
                                hint_bg_color: "red"
                                size_hint_y: None
                                height: "50dp"
                                on_value: root.atualizar_grafico(self.value)

                            MDBoxLayout:
                                size_hint_y: None
                                height: "40dp"
                                spacing: "2dp"
                                
                                MDBoxLayout:
                                    size_hint_x: 0.5
                                    md_bg_color: 0.2, 0.5, 0.8, 1
                                    radius: [5, 0, 0, 5]
                                
                                MDBoxLayout:
                                    id: barra_juros
                                    size_hint_x: 0.01  
                                    md_bg_color: 0.8, 0.2, 0.2, 1
                                    radius: [0, 5, 5, 0]

                            MDLabel:
                                id: lbl_legenda
                                text: "[color=#3380CC]Azul: O teu depósito[/color] | [color=#CC3333]Vermelho: Os Juros Mágicos[/color]"
                                markup: True
                                halign: "center"
                                font_style: "Caption"
                                adaptive_height: True

            # ==========================================
            # ABA 2: SIMULADOR (PRÁTICA)
            # ==========================================
            MDScreen:
                name: "aba_pratica"
                ScrollView:
                    MDBoxLayout:
                        orientation: 'vertical'
                        padding: "20dp"
                        spacing: "20dp"
                        adaptive_height: True

                        MDTextField:
                            id: input_capital
                            hint_text: "Capital Inicial (Ex: 1000)"
                            mode: "rectangle"
                            input_filter: "float"

                        MDTextField:
                            id: input_taxa
                            hint_text: "Taxa Mensal % (Ex: 1.5)"
                            mode: "rectangle"
                            input_filter: "float"

                        MDTextField:
                            id: input_tempo
                            hint_text: "Meses (Ex: 12)"
                            mode: "rectangle"
                            input_filter: "int"

                        MDRaisedButton:
                            text: "SIMULAR CRESCIMENTO"
                            pos_hint: {"center_x": .5}
                            on_release: root.simular_juros()

                        MDCard:
                            padding: "16dp"
                            radius: [10]
                            md_bg_color: 0.85, 0.95, 0.85, 1
                            adaptive_height: True
                            MDLabel:
                                id: lbl_resultado_juros
                                text: "Os resultados do teu algoritmo vão aparecer aqui."
                                halign: "center"
                                bold: True
                                size_hint_y: None
                                height: self.texture_size[1]

            # ==========================================
            # ABA 3: AMORTIZAÇÃO (TABELA DINÂMICA SAC)
            # ==========================================
            MDScreen:
                name: "aba_financiamento"
                ScrollView:
                    MDBoxLayout:
                        orientation: 'vertical'
                        padding: "15dp"
                        spacing: "15dp"
                        adaptive_height: True

                        # --- CARD DE ENTRADA DE DADOS ---
                        MDCard:
                            orientation: 'vertical'
                            padding: "15dp"
                            spacing: "10dp"
                            adaptive_height: True
                            radius: [15]
                            elevation: 1

                            MDLabel:
                                text: "Sistema de Amortização Constante (SAC)"
                                bold: True
                                font_style: "Subtitle2"
                                adaptive_height: True

                            MDGridLayout:
                                cols: 3
                                spacing: "10dp"
                                adaptive_height: True

                                MDTextField:
                                    id: input_sac_capital
                                    hint_text: "Valor (R$)"
                                    input_filter: "float"

                                MDTextField:
                                    id: input_sac_taxa
                                    hint_text: "Taxa (%)"
                                    input_filter: "float"

                                MDTextField:
                                    id: input_sac_tempo
                                    hint_text: "Meses"
                                    input_filter: "int"

                            MDRaisedButton:
                                text: "GERAR TABELA ALGORÍTMICA"
                                pos_hint: {"center_x": .5}
                                md_bg_color: 0.7, 0.3, 0.1, 1
                                on_release: root.gerar_tabela_sac()

                        # --- CARD PEDAGÓGICO: COMO LER A TABELA E PDF ---
                        MDCard:
                            orientation: 'vertical'
                            padding: "15dp"
                            spacing: "10dp"
                            adaptive_height: True
                            radius: [15]
                            md_bg_color: 0.9, 0.95, 1, 1

                            MDLabel:
                                text: "Como ler esta tabela?"
                                bold: True
                                font_style: "Subtitle2"
                                adaptive_height: True
                            
                            MDLabel:
                                text: "[b]Parcela:[/b] O que pagas no mês.\n[b]Amortização:[/b] O valor que realmente abate a tua dívida.\n[b]Juros:[/b] O lucro do banco naquele mês."
                                markup: True
                                font_style: "Caption"
                                adaptive_height: True
                            
                            MDSeparator:
                                height: "1dp"

                            MDBoxLayout:
                                adaptive_height: True
                                spacing: "10dp"
                                
                                MDIcon:
                                    icon: "file-pdf-box"
                                    theme_text_color: "Custom"
                                    text_color: 1, 0, 0, 1
                                    pos_hint: {"center_y": .5}
                                
                                MDTextButton:
                                    text: "Ler o Guia Completo do SAC"
                                    theme_text_color: "Custom"
                                    text_color: 0.2, 0.5, 0.8, 1
                                    pos_hint: {"center_y": .5}
                                    on_release: root.abrir_guia_sac()

                        # É aqui que o nosso Python vai injetar a Tabela Dinâmica
                        MDBoxLayout:
                            id: container_tabela
                            orientation: 'vertical'
                            adaptive_height: True
                            size_hint_y: None
                            height: "250dp"