<PerfilScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        md_bg_color: 0.95, 0.95, 0.97, 1
        MDTopAppBar:
            id: toolbar
            title: "Perfil"
            left_action_items: [["arrow-left", lambda x: root.voltar()]]
            right_action_items: [["pencil", lambda x: root.toggle_edit()]]
        
        ScrollView:
            MDBoxLayout:
                orientation: 'vertical'
                padding: "24dp"
                spacing: "20dp"
                adaptive_height: True
                
                MDBoxLayout:
                    orientation: 'vertical'
                    adaptive_height: True
                    spacing: "10dp"
                    MDIcon:
                        icon: "account-circle"
                        font_size: "80sp"
                        pos_hint: {"center_x": .5}
                        theme_text_color: "Primary"
                    MDTextField:
                        id: field_nome
                        text: app.user_name
                        hint_text: "Nome"
                        readonly: not root.edit_mode
                        mode: "line"
                        halign: "center"

                MDCard:
                    orientation: "vertical"
                    padding: "16dp"
                    spacing: "10dp"
                    radius: [15]
                    adaptive_height: True
                    MDTextField:
                        id: field_escola
                        text: app.escola
                        hint_text: "Escola"
                        readonly: not root.edit_mode
                    MDTextField:
                        id: field_turma
                        text: app.turma
                        hint_text: "Turma"
                        readonly: not root.edit_mode